# Generated by Django 5.0.1 on 2024-12-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApuestas', '0003_remove_juego_equipo1_remove_juego_equipo2_and_more'),
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostador',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Apostador',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
