# Generated by Django 5.0.1 on 2024-12-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_juego', models.CharField(max_length=50)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.administrador')),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='gestionApuestas.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='gestionApuestas.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('resultado_apuesta', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.apostador')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApuestas.juego')),
            ],
        ),
    ]
