# Generated by Django 5.0.1 on 2024-12-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApuestas', '0002_alter_juego_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='equipo1',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='equipo2',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='administrador',
        ),
        migrations.DeleteModel(
            name='Apuesta',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
