# Generated by Django 5.0.1 on 2024-12-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApuestas', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='tiempo_finalizacion',
        ),
    ]
