# Generated by Django 5.0.1 on 2024-12-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApuestas', '0006_equipo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='imagen',
        ),
    ]
