# Generated by Django 5.0.1 on 2024-12-09 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApuestas', '0007_remove_equipo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.BooleanField(default=False)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('equipo_apostado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApuestas.equipo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApuestas.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'juego')},
            },
        ),
    ]
